name: Build and Deploy to Azure (Docker Container)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container image to ACR
        run: |
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/pmps:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/pmps:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/pmps:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/pmps:latest

      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'howardlabpmps' # 需更換成您的 Web App 名稱
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.ACR_LOGIN_SERVER }}/pmps:${{ github.sha }}'
